# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

version: '3'

silent: true

includes:
  tools:
    taskfile: ./tools.yaml
    flatten: true

vars:
  ROOT_DIR:
    sh: pwd
  # OpenTelemetry Collector Builder settings
  OCB_VERSION: 0.142.0
  GOOS:
    sh: go env GOOS
  GOARCH:
    sh: go env GOARCH
  OCB_BINARY: ocb_{{.OCB_VERSION}}_{{.GOOS}}_{{.GOARCH}}
  OCB_URL: https://github.com/open-telemetry/opentelemetry-collector-releases/releases/download/cmd%2Fbuilder%2Fv{{.OCB_VERSION}}/{{.OCB_BINARY}}
  COLLECTOR_OUTPUT: ./slim-otelcol
  # Docker settings
  DOCKER_IMAGE: slim-otelcol
  DOCKER_TAG: latest

  MAIN_MODULE: github.com/agntcy/slim

  MODULES:
    sh: |
      find {{.ROOT_DIR}} -type f -name "go.mod" ! -path "./third-party/*" -exec dirname {} \; | \
        sort | \
        tr '\n' ' '

env:
  GOTOOLCHAIN: "go1.25.0+auto"

tasks:
  default:
    cmds:
      - task -l

  # go and code related tasks
  foreach-module:
    internal: true
    desc: Run task for each module
    cmds:
      - |
        set -e
        for dir in {{.MODULES}}; do
          pushd ${dir} > /dev/null
          echo "${dir}: running {{.CMD}}"
          {{.CMD}}
          popd > /dev/null
        done

  fetch-and-run:
    internal: true
    desc: Fetch and install bindings
    cmds:
      - task: foreach-module
        vars:
          CMD: go mod download
      - go run github.com/agntcy/slim-bindings-go/cmd/slim-bindings-setup

  modtidy:
    desc: Install go modules
    cmds:
      - task: foreach-module
        vars:
          CMD: go mod tidy

  lint:
    desc: Run go linter
    deps:
      - tools
    cmds:
      - task: foreach-module
        vars:
          CMD: "echo ${PWD} && {{.TOOLS_INSTALL_DIR}}/golangci-lint run"

  impi:
    desc: Run go impi
    deps:
      - tools
    cmds:
      - task: foreach-module
        vars:
          CMD: |
            {{.TOOLS_INSTALL_DIR}}/impi \
              --local github.com/agntcy/slim \
              --ignore-generated=true \
              --scheme stdThirdPartyLocal \
              ./...

  vuln:
    desc: Run go govulncheck
    deps:
      - tools
    cmds:
      - task: foreach-module
        vars:
          CMD: "{{.TOOLS_INSTALL_DIR}}/govulncheck ./..."

  coverage-reports:
    desc: Check test coverage
    deps:
      - tools
      - fetch-and-run
    cmds:
      - task: foreach-module
        vars:
          CMD: |
            {{.TOOLS_INSTALL_DIR}}/go-acc --output=$(basename  ${dir})-coverage.out ./...

  coverage:
    desc: Show coverage in browser
    deps:
      - coverage-reports
    cmds:
      - echo find . -name '*coverage.out' -execdir go tool cover -html=./{} \;

  test:
    desc: Run all tests for the SLIM exporter and receiver
    deps:
      - fetch-and-run
    cmds:
      - echo "Running slimexporter tests..."
      - cd exporter/slimexporter && go test -v
      - echo "Running slimreceiver tests..."
      - cd receiver/slimreceiver && go test -v
      - echo "Running internal/slim tests..."
      - cd internal/slim && go test -v

  # collector related tasks
  download-ocb:
    internal: true
    desc: Download OpenTelemetry Collector Builder for current architecture
    cmds:
      - echo "Downloading OCB {{.OCB_VERSION}} for {{.GOOS}}/{{.GOARCH}}..."
      - curl -L -o ocb "{{.OCB_URL}}"
      - chmod +x ocb
      - echo "OCB downloaded successfully"
    status:
      - test -f ocb

  collector:build:
    desc: Build the SLIM OpenTelemetry Collector including both slimexporter and slimreceiver
    deps:
      - download-ocb
      - fetch-and-run
    cmds:
      - echo "Generating collector sources..."
      - ./ocb --config builder-config.yaml --skip-compilation
      - echo "Compiling with CGO enabled..."
      - cd {{.COLLECTOR_OUTPUT}} && CGO_ENABLED=1 go build -trimpath -o slim-otelcol -ldflags="-s -w"
      - echo "Collector built successfully at {{.COLLECTOR_OUTPUT}}/slim-otelcol"

  collector:clean:
    desc: Clean the generated collector directory
    cmds:
      - go clean -cache -modcache
      - rm -rf {{.COLLECTOR_OUTPUT}}
      - echo "Collector build directory cleaned"

  collector:run:exporter:
    desc: Run the SLIM OpenTelemetry Collector Exporter
    cmds:
      - echo "Running SLIM OpenTelemetry Collector Exporter..."
      - "{{.COLLECTOR_OUTPUT}}/slim-otelcol --config {{.ROOT_DIR}}/exporter/slimexporter/example-exporter-collector-config.yaml"

  collector:run:receiver:
    desc: Run the SLIM OpenTelemetry Collector Receiver
    cmds:
      - echo "Running SLIM OpenTelemetry Collector Receiver..."
      - "{{.COLLECTOR_OUTPUT}}/slim-otelcol --config {{.ROOT_DIR}}/receiver/slimreceiver/example-receiver-collector-config.yaml"

  # Docker tasks
  docker:build:
    desc: Build Docker image for the SLIM OpenTelemetry Collector
    cmds:
      - echo "Building Docker image {{.DOCKER_IMAGE}}:{{.DOCKER_TAG}}..."
      - docker build -t {{.DOCKER_IMAGE}}:{{.DOCKER_TAG}} .
      - echo "Cleaning up temporary bindings..."
      - echo "Docker image built successfully"

  docker:run:
    desc: Run the SLIM collector in Docker
    cmds:
      - echo "Starting SLIM OpenTelemetry Collector container..."
      - >
        docker run --rm -p 4317:4317 -p 4318:4318
        -v {{.ROOT_DIR}}/collector-config.yaml:/etc/otel/config.yaml:ro
        {{.DOCKER_IMAGE}}:{{.DOCKER_TAG}}

  # Examples
  test:app:build:
    desc: Build the test app
    dir: testapp
    cmds:
      - echo "Building test app..."
      - go build -a .
      - echo "Test app built successfully"

  test:app:participant:
    desc: Run the test app as participant
    dir: testapp
    cmds:
      - echo "Running test app in participant mode..."
      - >
        go run .
        --app-name "agntcy/otel/receiver-app"
        --server "http://localhost:46357"
        --secret "a-very-long-shared-secret-0123456789-abcdefg"

  test:app:get-metrics:
    desc: Run the test app createing a challenge to get metrics
    dir: testapp
    cmds:
      - echo "Running test app creating a challenge to get metrics..."
      - >
        go run .
        --app-name "agntcy/otel/receiver-app-metrics"
        --server "http://localhost:46357"
        --secret "a-very-long-shared-secret-0123456789-abcdefg"
        --exporter-name-metrics "agntcy/otel/exporter-metrics"
        --channel-name-metrics "agntcy/otel/test-app-channel"

  test:app:get-traces:
    desc: Run the test app createing a challenge to get traces
    dir: testapp
    cmds:
      - echo "Running test app creating a challenge to get traces..."
      - >
        go run .
        --app-name "agntcy/otel/receiver-app-traces"
        --server "http://localhost:46357"
        --secret "a-very-long-shared-secret-0123456789-abcdefg"
        --exporter-name-traces "agntcy/otel/exporter-traces"
        --channel-name-traces "agntcy/otel/test-app-channel"

  test:app:get-all-signals:
    desc: Run the test app creating a challenge to get all signals (traces, metrics, logs)
    dir: testapp
    cmds:
      - echo "Running test app creating a challenge to get all signals..."
      - >
        go run .
        --app-name "agntcy/otel/receiver-app-all"
        --server "http://localhost:46357"
        --secret "a-very-long-shared-secret-0123456789-abcdefg"
        --exporter-name-traces "agntcy/otel/exporter-traces"
        --channel-name-traces "agntcy/otel/test-app-channel-traces"
        --exporter-name-metrics "agntcy/otel/exporter-metrics"
        --channel-name-metrics "agntcy/otel/test-app-channel-metrics"
        --exporter-name-logs "agntcy/otel/exporter-logs"
        --channel-name-logs "agntcy/otel/test-app-channel-logs"
  
  test:slim:run:
    desc: Run a SLIM node as a docker container for testing 
    cmds:
      - >
        docker run -it
        -v ./slim-test-config.yaml:/config.yaml -p 46357:46357
        ghcr.io/agntcy/slim:latest /slim --config /config.yaml
